document:
  debug:
    enabled: false
    parameters:
      highlight_links: true
      highlight_frames: false

  document_class:
    name: article
    size: 9pt

  remaining_height:
    lag: 4pt

  layout:
    dimensions:
      width: 158mm
      height: 210mm

    margin:
      top: 10mm
      bottom: 5mm
      left: 12mm
      right: 5mm

    margin_notes:
      width: 10mm
      separation: 1.9mm
      placement: left

parameters:
  template_name: mos
  compile:
    runs: 2
  parameters:
    header:
      title_position: right
      between_tables_spacing: 5mm
      skip: 1mm
      top_table:
        parameters:
          vertical_stretch: 1.3
          horizontal_spacing: 6pt
      quarterly_table:
        parameters:
          min_cell_height: 13mm
          horizontal_spacing: 0mm
          format: Y
          horizontal_lines: true
      monthly_table:
        parameters:
          min_cell_height: 11.1mm
          horizontal_spacing: 0mm
          format: Y
          horizontal_lines: true
    start_date: 2024, January
    end_date: 2024, December
    weekday_start: Monday
    show_week_numbers: true
    format_ampm: false
    week_number_placement: left
    notes:
      type: dotted
      parameters:
        horizontal_spacing_between_dots: 5mm
        vertical_spacing_between_dots: 5mm
    little_calendar:
      parameters:
        vertical_stretch: 1.2
        horizontal_spacing: 0mm
        show_week_numbers: true
        week_number_placement: left
    large_calendar:
      parameters:
        name_cell_height: 6mm
        cell_height: 2cm
        show_week_numbers: true
        week_number_placement: left
        day_number_shift: 1.5mm
        week_column_width: 6mm

sections:
  title:
    enabled: true
    parameters:
      name: 2024
      height: 3cm

  annual:
    enabled: true
    parameters:
      months_per_page: 12
      columns: 3
      underfull_vertical_spacing: 1cm
      little_calendar:
        parameters:
          width: 4.5cm

  quarterly:
    enabled: true
    parameters:
      calendars_column_position: left
      calendars_width: 5.8cm
      spacer_width: 3mm
      notes:
        parameters:
          width: 8cm
          height: 18cm
          shift_vertical: 4mm

  monthly:
    enabled: true
    parameters:

  weekly:
    enabled: true
    parameters:
      column_width: 3cm
      notes:
        parameters:
          width: 14cm
          height: 5.5cm
          shift_vertical: 2mm
          shift_horizontal: 1mm

  daily:
    enabled: true
    parameters:
      schedule_placement: left
      schedule_column_width: 5cm
      spacer_width: 0.5cm
      write_column_width: 8.6cm
      little_calendar:
        enabled: true
      schedule_label:
        enabled: true
      schedule:
        parameters:
          show_label: true
          from: '8:00'
          to: '20:30'
          hour_format: '24'
          line_height: 5mm
      todo_label:
        enabled: true
      todo:
        parameters:
          count: 10
          line_height: 5mm
      notes_label:
        enabled: true
        parameters:
          shift_vertical: 2mm
      notes:
        parameters:
          shift_vertical: 5mm
          shift_horizontal: 0.5mm
          width: 8.6cm
          height: 11.5cm
      personal_notes_label:
        enabled: false
        parameters:
          shift_vertical: 9mm
      personal_notes:
        enabled: false
        type: dotted
        parameters:
          shift_vertical: 5mm
          shift_horizontal: 1mm
          width: 5.5cm
          height: 4cm

  daily_notes:
    enabled: true
    parameters:
      pages: 1
      notes:
        parameters:
          shift_vertical: 4mm
          shift_horizontal: 1mm
          width: 14cm
          height: 18cm

  daily_reflect:
    enabled: true
    parameters:
      goals_label:
        enabled: true
        parameters:
          width: 6.75cm

      best_thing_label:
        enabled: true
        parameters:
          width: 6.75cm

      goals_and_best_thing_notes:
        type: dotted
        parameters:
          width: 14cm
          height: 3cm
          shift_vertical: 5mm
          shift_horizontal: 0.5mm

      gratitude_label:
        enabled: true
        parameters:
          shift_vertical: 9mm

      gratitude_notes:
        type: dotted
        parameters:
          width: 14cm
          height: 3cm
          shift_vertical: 5mm
          shift_horizontal: 0.5mm

      daily_log_label:
        enabled: true
        parameters:
          shift_vertical: 9mm

      daily_log_notes:
        type: dotted
        parameters:
          width: 14cm
          height: 8.5cm
          shift_vertical: 5mm
          shift_horizontal: 0.5mm

  index_notes:
    enabled: true
    parameters:
      index_pages: 4
      notes_per_page: 25
      index_table:
        parameters:
          line_height: 6.8mm
          lines_color: gray!50

      pages_per_note: 1
      notes:
        parameters:
          shift_vertical: 4mm
          shift_horizontal: 0.5mm
          width: 14cm
          height: 18cm

  index_todos:
    enabled: true
    parameters:
      index_pages: 4
      todos_per_page: 25
      index_table:
        parameters:
          line_height: 6.6mm
          lines_color: gray!50

      pages_per_todo: 1
      column_width: 6.75cm
      todos:
        parameters:
          line_height: 7mm
          count: 25

  about:
    enabled: true
